# Лабораторная работа №2
## Задание №1
Напишите программы, которые создают следующие массивы NumPy:

1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер
памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы.
Затем загрузите его и выведите на экран.

In [32]:
import numpy as np

In [33]:
a = np.array([1, 7, 13, 105])
print(a.nbytes, "байт")
np.savetxt("1.txt", a)
np.save("1.npy", a)
b = np.load("1.npy")
print(b)

16 байт
[  1   7  13 105]


2. Три массива: из 10 нулей, 10 единиц, 10 пятерок

In [34]:
a = np.zeros(10, dtype=np.int64)
b = np.ones(10, dtype=np.int64)
c = np.full(10, 5, dtype=np.int64)
print(a, b, c)

[0 0 0 0 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1 1] [5 5 5 5 5 5 5 5 5 5]


3. Массив последовательности четных целых чисел от 30 до 70.

In [35]:
a = np.arange(30, 72, 2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.

In [36]:
a = np.linspace(5, 50, 10, dtype=np.int64)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.

In [37]:
a = np.random.randint(1, 101, (3, 3, 3))
print(a)

[[[87 78 81]
  [81 13 29]
  [27 55 37]]

 [[51 54 47]
  [84 96 99]
  [79 30 84]]

 [[52 26 16]
  [33 40 19]
  [88 96 61]]]


6. Массив 3х4, заполненной значениями от 30 до 41.

In [38]:
a = np.arange(30, 42).reshape((3, 4))
print(a)

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0.

In [39]:
a = np.ones((10, 10), dtype=np.int64)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

In [40]:
a = np.diag([1, 2, 3, 4, 5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на главной диагонали.

In [41]:
a = np.zeros((4, 4), dtype=np.int64)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата

In [42]:
a = np.arange(np.datetime64('2017-03-01'), np.datetime64('2017-04-01'), dtype=np.datetime64)
print(a)

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


## Задание №2
Напишите следующие программы, используя подходящие функции модуля NumPy:

1. Дано два массива. Получите массив, состоящий из их общих элементов. Например, для массивов [0 10 20 40 60] и [10 30 40] ответом будет [10, 40].

In [43]:
a = np.array([0, 10, 20, 40, 60])
b = np.array([10, 30, 40])
c = np.intersect1d(a, b)
print(c)

[10 40]


2. Дан массив. Получите массив его уникальных элементов.
Исходный массив: [10 10 20 20 30 30]
Массив его уникальных элементов: [10 20 30]
Исходный массив:
[[1 1]
[2 3]]
Массив его уникальных элементов: [1 2 3]

In [44]:
a = np.array([[1, 1],[2,3]])
c = np.unique(a)
print(c)

[1 2 3]


3. Дан массив. Получите два массива: его уникальные элементы и их частоты.
Исходный массив: [10 10 20 10 20 20 20 30 30 50 40 40]
Два массива: [10 20 30 40 50], [3 4 2 2 1]

In [45]:
a = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
unique, counts = np.unique(a, return_counts=True)
print(unique, counts)

[10 20 30 40 50] [3 4 2 2 1]


4. Дан массив. Получите массив путем повторения данного.
Образец массива: [1, 2, 3, 4]
Ожидаемый результат:
1 повторение
[1, 2, 3, 4]
2 повторения
[1, 2, 3, 4, 1, 2, 3, 4]
3 повторения
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [46]:
a = np.array([1, 2, 3, 4])
n = int(input("Число повторений: "))
c = np.tile(a, n)
print(c)

Число повторений: 3
[1 2 3 4 1 2 3 4 1 2 3 4]


5. Дан массив, в котором имеются значения nan. Получите массив, удалив все значения
nan.
Исходный массив: [200. 300. nan nan nan 700.]
После удаления значений nan: [200. 300. 700.]
Исходный массив:
[[1. 2. 3.]
[nan 0. nan]
[6. 7. nan]]
После удаления значений nan: [1. 2. 3. 0. 6. 7.]

In [47]:
a = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
a = a[~np.isnan(a)]
print(a)

[200. 300. 700.]


6. Дан массив. Получите массив его k наименьших значений.
Оригинальный массив: [1. 7. 8. 2. 0.1 3. 15. 2.5]
Его 4 наименьших значения: [0.1 1. 2. 2.5]


In [48]:
a = np.array([1., 7., 8., 2., 0.1, 3., 15., 2.5])
k = int(input("Число наименьших значений: "))
a = np.sort(a)
c = a[:k]
print(c)

Число наименьших значений: 4
[0.1 1.  2.  2.5]


7. Дан массив и некоторое число. Найдите ближайший по значению к числу элемент
массива.
Исходный массив: [0.5 1.8 2.1 3.5 4.87 5.13 6.49]
Значение для сравнения: 3,09066280756759
Ответ: 3.5

In [49]:
a = np.array([0.5, 1.8, 2.1, 3.5, 4.87, 5.13, 6.49])
x =  3.09066280756759
print(a[np.nanargmin(np.absolute(a - x))])

3.5


8. Дано два массива со строками. Получите массив при помощи поэлементного
объединения.
1 массив: ['Python' 'PHP']
2 массив: ['Java' 'C ++']
Результат: ['Python Java' 'PHP C ++']

In [60]:
a = np.array(['Python', 'PHP'], dtype=np.str_)
b = np.array([' Java', ' C++'], dtype=np.str_)
c = np.char.add(a, b)
print(c)

['Python Java' 'PHP C++']


9. Дан массив строк. Получите массив с частотой встречаемости буквы «P».
Оригинальный массив: ['Python' 'PHP' 'JS' ' examples' 'html']
Количество 'P': [1 2 0 0 0]

In [84]:
a = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str_)
print(np.char.count(a, 'P'))

[1 2 0 0 0]


10. Найдите корни следующих полиномов:
a. x^2 - 4х + 7
b. x^4 - 11х^3 + 9х^2 + 11х - 10

In [62]:
a = [1, -4, 7]
print(np.roots(a))
b = [1, -11, 9, 11, -10]
print(np.roots(b))

[2.+1.73205081j 2.-1.73205081j]
[10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]


## Задание №3
Напишите программу, которая будет решать систему линейных уравнений вида:
![](img/1.png)
Коэффициенты и правую часть вводит пользователь. Программа выводит решение
системы. Для нахождения решения используйте numpy.linalg.solve.
Система не имеет решения (или имеет их бесконечно много), если определитель матрицы
коэффициентов равен 0. В этом случае необходимо выводить соответствующее сообщение.
Для нахождения определителя используйте функцию numpy.linalg.det.

In [83]:
a = np.array(input("Коэффициенты: ").split(), dtype='f').reshape(2, 2)
b = np.array(input("Правая часть: ").split(), dtype='f').reshape(2, 1)
det = np.linalg.det(a)
if det == 0:
    print("Опеределитель матрицы нулевой")
else:
    c = np.linalg.solve(a, b)
    print("Ответ: ", *c)

Коэффициенты: 4 3 2 1
Правая часть: 4 3
Ответ:  [2.5] [-2.]
